### PR TITLE
Modify the inefficiency of dropout kernel.

### PR DESCRIPTION
**Pull request by sgkim126**

### CODE REVIEW

**Comment by scottlegrand** [comment]
Reject, not more efficient when multithreaded.  Which is to say that it
*would* be more efficient single-threaded, but when executing in 32-way
SIMD, effectively all paths are taken.  This is why the code is written
this way, in the hopes that predication is picked up by the compiler.  What
you *could* do is do this on the memory read, but even then, if p is 0.5 or
so, you're mostly guaranteed to hit a full memory load.

That said, I'm open-minded, did you time this?

Scott

**Comment by sgkim126** [comment]
@scottlegrand I don't understand `This is why the code is written this way, in the hopes that predication is picked up by the compiler`. Could you explain more?

**Comment by sgkim126** [comment]
Anyway, the current code are inefficient.
It's hard to notice by execution, because calculating dropout is very short job and does not affect performance.
So we should see how it compiles.
In Pascal architecture, original code is compied as below
```
    .reg .pred  %p<4>;
    .reg .f32   %f<10>;
    .reg .b32   %r<6>;
    .reg .b64   %rd<10>;


    ld.param.u64    %rd3, [_Z24kCalculateDropout_kernelPfS_ffm_param_0];
    ld.param.u64    %rd4, [_Z24kCalculateDropout_kernelPfS_ffm_param_1];
    ld.param.f32    %f4, [_Z24kCalculateDropout_kernelPfS_ffm_param_2];
    ld.param.f32    %f5, [_Z24kCalculateDropout_kernelPfS_ffm_param_3];
    ld.param.u64    %rd5, [_Z24kCalculateDropout_kernelPfS_ffm_param_4];
    mov.u32     %r1, %ctaid.x;
    mov.u32     %r2, %ntid.x;
    mov.u32     %r3, %tid.x;
    mad.lo.s32  %r4, %r2, %r1, %r3;
    cvt.u64.u32 %rd1, %r4;
    setp.ge.u64 %p1, %rd1, %rd5;
    @%p1 bra    BB46_5;

    cvta.to.global.u64  %rd6, %rd3;
    cvta.to.global.u64  %rd7, %rd4;
    shl.b64     %rd8, %rd1, 2;
    add.s64     %rd9, %rd7, %rd8;
    ld.global.f32   %f1, [%rd9];
    setp.lt.ftz.f32 %p2, %f1, %f4;
    add.s64     %rd2, %rd6, %rd8;
    @%p2 bra    BB46_3;
    bra.uni     BB46_2;

BB46_3:
    mov.u32     %r5, 0;
    st.global.u32   [%rd2], %r5;
    mov.f32     %f9, 0f00000000;
    bra.uni     BB46_4;

BB46_2:
    ld.global.f32   %f9, [%rd2];

BB46_4:
    selp.f32    %f7, 0f00000000, %f9, %p2;
    mul.ftz.f32     %f8, %f7, %f5;
    st.global.f32   [%rd2], %f8;

BB46_5:
    ret;
```
And my kernel code is compiled as
```
    .reg .pred  %p<3>;
    .reg .f32   %f<9>;
    .reg .b32   %r<5>;
    .reg .b64   %rd<10>;


    ld.param.u64    %rd3, [_Z24kCalculateDropout_kernelPfS_ffm_param_0];
    ld.param.u64    %rd4, [_Z24kCalculateDropout_kernelPfS_ffm_param_1];
    ld.param.f32    %f3, [_Z24kCalculateDropout_kernelPfS_ffm_param_2];
    ld.param.f32    %f4, [_Z24kCalculateDropout_kernelPfS_ffm_param_3];
    ld.param.u64    %rd5, [_Z24kCalculateDropout_kernelPfS_ffm_param_4];
    mov.u32     %r1, %ctaid.x;
    mov.u32     %r2, %ntid.x;
    mov.u32     %r3, %tid.x;
    mad.lo.s32  %r4, %r2, %r1, %r3;
    cvt.u64.u32 %rd1, %r4;
    setp.ge.u64 %p1, %rd1, %rd5;
    @%p1 bra    BB46_4;

    cvta.to.global.u64  %rd6, %rd3;
    cvta.to.global.u64  %rd7, %rd4;
    shl.b64     %rd8, %rd1, 2;
    add.s64     %rd9, %rd7, %rd8;
    ld.global.f32   %f6, [%rd9];
    setp.lt.ftz.f32 %p2, %f6, %f3;
    add.s64     %rd2, %rd6, %rd8;
    mov.f32     %f8, 0f00000000;
    @%p2 bra    BB46_3;

    ld.global.f32   %f7, [%rd2];
    mul.ftz.f32     %f8, %f7, %f4;

BB46_3:
    st.global.f32   [%rd2], %f8;

BB46_4:
    ret;
```
The original code does more access to global memory and has more branches.

Access to globla memory can make code slow because caching global memory is not guaranteed.

And branches makes code much slower in SIMD than single threaded, because Nvidia GPU executes 32 thread with a single program counter.

**Comment by scottlegrand** [comment]
Mea culpa, massive jetlag from flying back from Asia, the split diff view
makes it clear that your change is a great one.

**Pull request merged**
