### PR TITLE
CNN Support for DSSTNE

### PR DESCRIPTION
**Pull request by scottlegrand**
Adds CNN support with some bugs fixed along the way, cleans up weight update code a bit, and provides a CIFAR-10 example

### CODE REVIEW

**Comment by tristanpenman** [comment]
I have had some trouble getting the CIFAR-10 example to work on a Titan X GPU. This may take a while to fully resolve, so I have cherry-picked the first two commits from this PR into master. This will allow other development to continue while we resolve these issues.

**Comment by scottlegrand** [comment]
I found the line of code that causes this, it's the uint8_t conversion in
kernels.cu.  Now I have to figure out *why* this is causing this and why it
doesn't affect CIFAR-100.

**Comment by scottlegrand** [comment]
Going further, all image data is now zero.  Digging...

**Comment by scottlegrand** [comment]
"train" should be "training" in dparse.cpp, checking in fix shortly...

**Comment by tristanpenman** [comment]
Thanks for looking into it @scottlegrand. Nice to see that it was an easy fix.

**Comment by scottlegrand** [comment]
These things usually are.  The important thing to do is root cause rather
than patch IMO.

**Pull request merged**
