### PR TITLE
Ignore compiled files.

### PR DESCRIPTION
**Pull request by sgkim126**
This patch is picked from #85.
And also ignore the build directories in tst.

### CODE REVIEW

**Comment by romerocesar** [comment]
Keep all .gitignore patterns in a single .gitignore file in the root of the repo. Given how small and how infrequent .gitignore changes, it's easier to keep it in a single file rather than spread out throughout the repo

**Comment by sgkim126** [comment]
Using a single gitignore file is good for most cases.
But empirically if there are multiple build directories(in this case tst/unittests, tst/gputests and src/amazon/dsstne), using gitignore files per directory prevents mistakes in the future.(ex. rename the directory)

If you think a single ignore file is still good, I'll update it. But I'm requesting to consider it once more.

**Comment by tristanpenman** [comment]
The .gitignore files for the 'build' directories are not appropriate, as they are user-defined build artifacts. Someone building DSSTNE locally is free to place their build wherever they like. 

They may be hard-coded in the Travis CI config file, but this ability to choose a build location is one of the reasons why CMake was adopted for the test suite.

**Comment by sgkim126** [comment]
Yes, I picked the test path from the travis file.
I'll not ignore the build directory of tests if the path is not decided to use by developers.

However I think your team should decide the directory name for test builds and add the path to .gitignore files and. If not, anyone who modifies the tests will be afraid to commit the wrong files.

**Comment by sgkim126** [comment]
By the way how about the .gitignore file path.
I still prefer the current path. Placing it on the same path with Makefile was better in my experience. But I'm ready for moving it to root of the repo.

**Comment by tristanpenman** [comment]
@sgkim126, I'm happy to merge this once it has been moved to the root of the repo. That will provide the most benefit In the long term.

**Pull request merged**
